#!/bin/sh

show_help(){

    printf 'Usage:
    sv-disable <service-names>

    Disabling a service will make it not autostart
'
}
if [ -z "$1" ];then
    show_help
    exit 1
fi
if [ -u "$SVDIR" ];then
    >&2 echo "Error: SVDIR not set"
    exit 1
fi
for s in "$@"; do
    echo "disable $s"
    touch "$SVDIR/$s/down"
    sv down $s
done
