#!/bin/sh

show_help(){

    printf 'Usage:
    sv-enable <service-names>

    Enabling a service will make it autostart
'
}
if [ -z "$1" ];then
    show_help
    exit 1
fi
if [ -u "$SVDIR" ];then
    >&2 echo "Error: SVDIR not set"
    exit 1
fi
for s in "$@"; do
    echo "enable $s"
    rm -f "$SVDIR/$s/down"
    sv up $s
done
